export const SET_RECOMMENDED_MOVIES = 'SET_RECOMMENDED_MOVIES';
export const SET_TRENDING_MOVIES = 'SET_TRENDING_MOVIES';
export const SET_NEW_RELEASES = 'SET_NEW_RELEASES';
export const SET_TOP_RATED_MOVIES = 'SET_TOP_RATED_MOVIES';
export const SET_GENRES = 'SET_GENRES';
export const SET_MOVIES_BY_GENRE = 'SET_MOVIES_BY_GENRE';
export const SET_LOADING = 'SET_LOADING';
